version: "3.5"

services:
  rstudio:
    image: ajall1985/gmri_rocker
    build: .
    ports:
      - "8787:8787"
      #volumes:
      #- ~/GitHub/TargetsSDM:/home/aallyn/TargetsSDM
    env_file:
      - ./secret.env
