version: "3.3"

services:
  rstudio:
    # Here is how you could add data from a folder on Box
    volumes:
        - ~/Box/RES Data/Shapefiles:/data/Shapefiles
        - ~/Box/Mills Lab/Projects/ForecastingChallenge:/ForecastingChallenge
     