version: "3.8"

services:
  rstudio: 
    image: ajall1985/gmri_rocker
    build: .
    ports: 
      - "8787:8787"
    volumes:
        # Local data
      - ~/Desktop/Docker Data Testing:/home/rstudio/Docker Data Testing
    #env_file:
      #- ./secret.env