version: "3.8"

services:
  rstudio:
    volumes:
      # Connect to the research folder on box for access to shapefiles
      - ~/Box/RES Data/Shapefiles/NELME_regions:/home/rstudio/NELME_regions
     