version: "3.8"

services:
  rstudio: 
    image: ajall1985/gmri_rocker
    build: .
    ports: 
      - "8787:8787"
    volumes:
      # Local data
      - type: volume
        source: ~/Desktop/Docker Data Testing
        target: /home/Docker Data Testing
        volume:
          nocopy: true
    #env_file:
      #- ./secret.env