version: "3.3"

services:
  rstudio: 
    image: ajall1985/gmri_rocker
    build: .
    ports: 
      - "8787:8787"
    volumes:
      - $HOME/:/home/aallyn/
      - /mnt/volume_nyc1_01/:/home/aallyn/block_storage/
      # Here is how you would add data from a local folder
      #- ./DataTest:/home/rstudio/DataTest
      # Adding GIT information -- this might be causing an error?
      #- ~/.gitconfig:/etc/gitconfig
    env_file:
      - ./secret.env