version: "3.3"

services:
  rstudio: 
    image: ajall1985/gmri_rocker
    build: .
    ports: 
      - "8787:8787"
    volumes:
      # This will work if docker container is started on local host, doesn't work with a droplet
      # - ~/GitHub/sdm_workflow/scratch/aja/TargetsSDM:/home/aallyn/TargetsSDM
    env_file:
      - ./secret.env