#####
## Additional libraries and functions to source along with those included with the rocker/geospatial image
#####

# New as of 02/16/2022
install.packages("devtools")
install_github("james-thorson/VAST", INSTALL_opts = "--no-staged-install")
install.packages("splines")
install.packages("tidyverse")
install.packages("lubridate")
install.packages("sf")
install.packages("here")
install.packages("targets")
install.packages("tarchetypes")
install.packages("raster")
devtools::install_github("thomasp85/patchwork")
install.packages("gifski")

# Old implementation
# install.packages("Matrix", version = "1.2.8")
# devtools::install_version("TMB", "1.7.18")
# install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
## install.packages('udunits2', type = 'source', repo = 'cran.rstudio.com', configure.args = c(udunits2 = "--with-udunits2-lib=/usr/local/lib"))
## install.packages('units', type = 'source', repo = 'cran.rstudio.com', configure.args = c(units = "--with-udunits2-lib=/usr/local/lib"))
# devtools::install_github("james-thorson/FishStatsUtils", ref = "2.9.1", INSTALL_opts="--no-staged-install")
# devtools::install_github("james-thorson/VAST", ref = "3.7.1", INSTALL_opts="--no-staged-install")
## devtools::install_github("james-thorson/FishStatsUtils", ref = "2.9.1", INSTALL_opts="--no-staged-install", configure.args = c(udunits2 = "--with-udunits2-include=/usr/include/udunits2"))
## devtools::install_github("james-thorson/VAST", ref = "3.7.1", INSTALL_opts="--no-staged-install", configure.args = c(udunits2 = "--with-udunits2-include=/usr/include/udunits2"))
## devtools::install_github("james-thorson/FishData")
# install.packages("sf")
# install.packages("here")
# install.packages("googledrive")
# install.packages("snakecase")
# devtools::install_github("ropensci/rnaturalearthdata")
# devtools::install_github("thomasp85/patchwork")
# install.packages("doFuture", version = "0.11.0")
# install.packages("parallel")
# install.packages("doParallel", version = "1.0.15")
# install.packages("conflicted")
# install.packages("future")
# install.packages("furrr")
# install.packages("targets")
# install.packages("tarchetypes")
# install.packages("splines")
# install.packages("effects")
# install.packages("gifski")
# install.packages("akima")
# install.packages("tictoc")
# devtools::install_github("https://github.com/gulfofmaine/gmRi")